### PR TITLE
Use non-zero delegation fees

### PR DESCRIPTION
**Pull request by cducrest**
Replace relay config.json for config.toml
Copy out an address of a deployed currency network to config.toml for delagation fees currency network.
Allows to have e2e tests with a non-zero value for delegation fees.

Probably not the cleanest but not so complex.

### CODE REVIEW

**Comment by cducrest** [comment]
I investigate why e2e tests are failing, it seems it is because they use a hard coded value of 0 for the fees instead of asking for them.

**Review by ghost — CHANGES_REQUESTED** [review]
Please replace the the call to `sed --in-place` with the use of a here document and inline the config.toml:

Something like the following should work:

```bash
cat >${relay_config} <<EOF
[relay]
syncInterval = 300
updateNetworksInterval = 5
enableEtherFaucet = true
enableRelayMetaTransaction = true
enableDeployIdentity = true

[relay.rpc]
host = "node"
port = 8545
ssl = false

[[relay.delegationFees]]
value = 1
currencyNetwork = "${first_network_address}"
EOF
```

Besides being easier to read, this has the benefit of not changing files that are managed by git.
Another solution would be to cat the 'constant' part together with just one section.

**Comment by cducrest** [comment]
I don't get it. If I replace the `sed -i` command with this cat command, the file is still modified. It is easier to read but I end up with the same data in two places: the relay config is both in the bash script and in `config.toml` while it should only be modified in the bash script.

**Comment by ghost** [comment]
> I don't get it. If I replace the sed -i command with this cat command, the file is still modified

You should remove the file from git in that case.

**Review by ghost — APPROVED** [review]
LGTM 

FYI jq would allow to extract values from json files from a bash script: https://stedolan.github.io/jq/

(but it's another dependency you have to install)

**Pull request merged**
